export const TODO_INIT_FETCH_START = "TODO_INIT_FETCH_START";
export const TODO_INIT_FETCH_SUCCESS = "TODO_INIT_FETCH_SUCCESS";
export const TODO_INIT_FETCH_FAIL = "TODO_INIT_FETCH_FAIL";

export const TODO_ADD_ITEM_POST_SUCCESS = "TODO_ADD_ITEM_POST_SUCCESS";
export const TODO_ADD_ITEM_POST_FAIL = "TODO_ADD_ITEM_POST_FAIL";
